config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'flights#index'

  resources :bookings, only: [:new,:create,:show]
end

app/models/airport.rb
class Airport < ApplicationRecord

	has_many :departing_flights, :foreign_key => :start_id, :class_name => "Flight"
	has_many :arriving_flights,  :foreign_key => :finish_id, :class_name => "Flight"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
	has_many :booking_passengers
	has_many :passengers, :through => :booking_passengers
	belongs_to :flight

	accepts_nested_attributes_for :passengers
end

app/models/booking_passenger.rb
class BookingPassenger < ApplicationRecord
	belongs_to :booking
	belongs_to :passenger
end

app/models/flight.rb
class Flight < ApplicationRecord
	has_many :bookings

	belongs_to :from_airport, :foreign_key => "start_id", :class_name => "Airport"
	belongs_to :to_airport,   :foreign_key => "finish_id", :class_name => "Airport"

	def self.get_dates
		flight_date = Flight.find_by_sql("SELECT start_date FROM flights")
	end

	def date_formatted
		start_date.strftime("%m/%d/%Y")
	end

	def self.search_flight(params)
		#flights = Flight.
	end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
	has_many :booking_passengers
	has_many :bookings, :through => :booking_passengers
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

	def new
		@flight = Flight.find(params[:flight])
		@booking = @flight.bookings.build
		params[:passenger_number].to_i.times { @booking.passengers.build }
	end

	def create
		@flight = Flight.find(params[:booking][:flight_id])
		@booking = @flight.bookings.build(booking_params)
		if @booking.save
			flash[:success] = "Booking succesful"
			flash[:info] = "You can always check your email to see your booking information!"
			@booking.passengers.each { |p| TicketMailer.booking_information(p).deliver_now }
			redirect_to @booking
		else
			flash.now[:danger] = "Booking unsuccessful"
			render 'new'
		end
	end

	def show
		@booking = Booking.find(params[:id])
	end

	private

		def booking_params
			params.require(:booking).
				permit(passengers_attributes: [:name, :email])
		end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
	def index
		@to_options = Airport.all.map{ |a| [a.code, a.id] }
		@from_options = Airport.all.map { |a| [a.code, a.id] }
		@number_of_passengers = (1..4).to_a.map{ |num| [num,num]}
		@flight_dates = Flight.all.map{ |f| [f.start_date, f.id] }
	
		if params[:from_options]
			@date_format = params[:flight_date].in_time_zone.to_i
			@found = Flight.where('start_id = ? AND finish_id = ?', 
														params[:from_options], params[:to_options] )
			@found = @found.reject{ |r| r.start_date.to_i != @date_format }
			@passengers = params[:passengers]
		end


	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<h1>New Booking:</h1>

<ul>
	<li>Date: <%= @flight.start_date %></li>
	<li>Airports:
		<li>To: <%= @flight.to_airport.code %></li>
		<li>From: <%= @flight.from_airport.code %></li>
	</li>
	<li>Flight ID: <%= @flight.id %></li>
</ul>

<%= form_for @booking do |f| %>
	<%= render 'shared/error_messages' %>
    <%= f.hidden_field :flight_id, :value => @flight.id %>
	Passengers:
	<ul>
		<%= f.fields_for :passengers do |passenger_form| %>
			<li>
				<%= passenger_form.label :name %>
				<%= passenger_form.text_field :name %>
				
				<br>
				<%= passenger_form.label :email %>
				<%= passenger_form.text_field :email %>

			</li>
			<br>
		<% end %>
	</ul>
	<%= f.submit "Submit" %>
<% end %>

app/views/bookings/show.html.erb
<h1>Booking <%= @booking.id %></h1>

app/views/flights/index.html.erb
<h1>Flight Index</h1>

<div class="container">
	<p>Enter a date or an airport: </p>
	<%= form_tag(root_url, method: "get") do %>
		<%= label_tag(:to_options, "To:") %>
		<%= select_tag(:to_options, options_for_select(@to_options)) %>

		<%= label_tag(:from_options, "From:") %>
	    <%= select_tag(:from_options, options_for_select(@from_options)) %>
		
		<%= label_tag(:passengers, "Passengers:") %>
		<%= select_tag(:passengers, options_for_select(@number_of_passengers)) %>

		<%= label_tag(:flight_date, "Date: ") %>
		<%= select_tag(:flight_date, options_from_collection_for_select(Flight.get_dates, 'start_date',
						:date_formatted)) %>

	    <%= submit_tag("Search") %>
	<% end %>
</div>

<% if @found %>
	<p>Results: Choose a Flight </p>
	
	<%= form_tag(new_booking_url, method: "get") do %>
		<% @found.each do |flight| %>
			<%= radio_button_tag(:flight, flight.id) %>
			<%= label_tag("flight-#{flight.id}", "Flight No: #{flight.id}")%>
		
		<% end %>
		<%= hidden_field_tag(:passenger_number, @passengers ) %>
		<br>
		<%= submit_tag("Submit") %>
	<% end %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<div class="container">
		<% flash.each do |message_type, message| %>
			<div class="alert alert-<%= message_type %>"><%= message %></div>
		<% end %>
		<%= yield %>
	</div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @booking.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(@booking.errors.count, "error") %>
		</div>
		<ul>
			<% @booking.errors.full_messages.each do |msg| %>
				<li> <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>